### ISSUE TITLE
why add one 

### ISSUE THREAD

**Issue by Tzy010822** [Advocate99/DragDiffusion#1]
resume_times = pipe.scheduler.timesteps[list(pipe.scheduler.timesteps).index(inter_id)+1:] 
wonder why add one here

**Comment by Advocate99** [comment]
Hi, do you mean why we need this one or why this one locates here?
The resume times is used in the reverse process. When the timestep corresponding to the latent to be optimized is set, the reverse process starts from the set timestep and continues noise prediction in the unfinished steps.
I update the location of the lines because I align the mask loss to the paper in the recent commit (I use the mask loss based on the features, not the latent in the first commit). And in this procedure, pipe should set the timesteps first, and for the resume_times, the adjustment of the location has no meaning.

**Comment by Advocate99** [comment]
Hi, thanks.
Maybe this is a bug and the 1 should be removed.
But the performances seem to be the similar because the noisy input won't change a lot.
